// GUI/PAGES
// THIS IS WHERE THE DEVICE DISPLAY PAGES ARE DEFINED
// AND HOME OF THE TOUCH CONTROLLER TASK THAT HANDLES THEM.
// TASK IS DESIGNED TO SLEEP WHEN NOT USED FOR A MASSIVE BATTERY REDUCTION COST 

use embassy_futures::select::{select, Either};

use crate::components::ft3168::{Ft3168Touch, Gesture, SwipeDirection, TouchPoint};
use crate::*;

// ───────────────────────────────────────────────────────────────────────
// TOUCH TYPES FOR THE TOUCH TASK
pub static TOUCH_EVENTS: embassy_sync::signal::Signal<
    embassy_sync::blocking_mutex::raw::CriticalSectionRawMutex,
    TouchEvent,
> = embassy_sync::signal::Signal::new();

#[derive(Clone, Copy, defmt::Format)]
pub enum TouchEvent {
    Tap { x: u16, y: u16 },
    Swipe(crate::components::ft3168::SwipeDirection, u16, u16),
}

// THIS SETS THE HOMESCREEN TO CLOCK PAGE
crate::init_u8!(CURRENT_PAGE, 1);

// HOW OFTEN I2C IS POLLED (WHEN FINGER IS ON SCREEN ONLY)
const TRACKING_POLL_INTERVAL: embassy_time::Duration = embassy_time::Duration::from_millis(10);

const DOUBLE_TAP_MAX_DISTANCE: u16 = 50;
const DOUBLE_TAP_TIMEOUT: embassy_time::Duration = embassy_time::Duration::from_millis(400);

// PIXELS FROM THE EDGE OF THE DISPLAY
const BOTTOM_SWIPE_THRESHOLD: u16 = 40;
const TOP_SWIPE_THRESHOLD: u16 = 40;

// ───────────────────────────────────────────────────────────────────────
// PAGE DEFINITIONS – macro 
crate::define_pages! {
    // MAIN PAGES
    Apps        = 0,  is_settings: false, prev: None, next: None;
    Clock       = 1,  is_settings: false, prev: None, next: None;
    Battery     = 2,  is_settings: false, prev: None, next: None;
    Weather     = 3,  is_settings: false, prev: None, next: None;

    // APPS
    MediaPlayer = 10, is_settings: false, prev: None, next: None;
    DuckTv      = 11, is_settings: false, prev: None, next: None;
    DuckCloud   = 13, is_settings: false, prev: None, next: None;
    Settings    = 14, is_settings: true,  prev: None, next: SettingsWifi;

    // SPECIAL PAGES
    Call      = 100, is_settings: false, prev: None, next: None;
    Text      = 101, is_settings: false, prev: None, next: None;
    TextInput = 102, is_settings: false, prev: None, next: None;
    Gallery   = 103, is_settings: false, prev: None, next: None;

    // SETTINGS SUBPAGES
    SettingsWifi    = 140, is_settings: true, prev: SettingsInfo,    next: SettingsRssi,    tap: wifi;
    SettingsRssi    = 141, is_settings: true, prev: SettingsWifi,    next: SettingsBle;
    SettingsBle     = 142, is_settings: true, prev: SettingsRssi,    next: SettingsApi,     tap: bluetooth;
    SettingsApi     = 143, is_settings: true, prev: SettingsBle,     next: SettingsWake,    tap: api;
    SettingsWake    = 144, is_settings: true, prev: SettingsApi,     next: SettingsStream,  tap: wakeword;
    SettingsStream  = 145, is_settings: true, prev: SettingsWake,    next: SettingsSpeaker, tap: streaming;
    SettingsSpeaker = 146, is_settings: true, prev: SettingsStream,  next: SettingsMic,     swipe: speaker, tap: speaker;
    SettingsMic     = 147, is_settings: true, prev: SettingsSpeaker, next: SettingsDisplay, swipe: mic,      tap: mic;
    SettingsDisplay = 148, is_settings: true, prev: SettingsMic,     next: SettingsTimeout, swipe: display,  tap: display;
    SettingsTimeout = 149, is_settings: true, prev: SettingsDisplay, next: SettingsAmp;
    SettingsAmp     = 150, is_settings: true, prev: SettingsTimeout, next: SettingsCpu,    tap: amplifier;
    SettingsCpu     = 151, is_settings: true, prev: SettingsAmp,     next: SettingsSleep,  swipe: cpu;
    SettingsSleep   = 152, is_settings: true, prev: SettingsCpu,     next: SettingsSsh,   swipe: sleep;
    SettingsSsh     = 153, is_settings: true, prev: SettingsSleep,    next: SettingsVpn,    tap: ssh;
    SettingsVpn     = 154, is_settings: true, prev: SettingsSsh,    next: SettingsInfo,   tap: vpn;    
    SettingsInfo    = 155, is_settings: true, prev: SettingsVpn,   next: SettingsWifi,   swipe: info;

}


// MAIN NAVIGATION (NOT GENERATED BY THE MACRO)
impl Page {
    pub fn next_main(&self) -> Self {
        match self {
            Page::Apps    => Page::Clock,
            Page::Clock   => Page::Battery,
            Page::Battery => Page::Weather,
            Page::Weather => Page::Weather, // STOP – NO FURTHER
            _             => Page::Clock,
        }
    }

    pub fn prev_main(&self) -> Self {
        match self {
            Page::Clock   => Page::Apps,
            Page::Battery => Page::Clock,
            Page::Weather => Page::Battery,
            Page::Apps    => Page::Apps, // STOP – NO FURTHER
            _             => Page::Clock,
        }
    }
    
    // MAIN APPLICATIONS (CLOSED BY SWIPING UP FROM BOTTOM OF DISPLAY)
    pub fn is_app_page(&self) -> bool {
        self.is_settings_page()
            || matches!(self, Page::MediaPlayer | Page::DuckTv | Page::DuckCloud)
    }

    // FETCHES PAGE NUMBER AS RAW u8
    pub fn as_raw(self) -> u8 { self as u8 }
}

// ───────────────────────────────────────────────────────────────────────
// INTERNAL HELPERS FOR THIS MODULE
fn set_page(page: Page) {
    crate::store!(CURRENT_PAGE, page.as_raw());
}

pub fn current_page() -> Page {
    let raw = crate::load!(CURRENT_PAGE);
    Page::from_raw(raw).unwrap_or(Page::Clock)
}

// ───────────────────────────────────────────────────────────────────────
// PROCESS A FINISHED GESTURE (SWIPE OR TAP). ON LAUNCHER A TAP IS STORED AS PENDING,
// OTHER PAGES IT'S INSTANT!
async fn process_gesture(
    start_x: u16,
    start_y: u16,
    last_x: u16,
    last_y: u16,
    pending_tap: &mut Option<(u16, u16, embassy_time::Instant, Page)>,
) {
    let dx = last_x as i32 - start_x as i32;
    let dy = last_y as i32 - start_y as i32;
    let abs_dx = dx.unsigned_abs();
    let abs_dy = dy.unsigned_abs();

    let direction = if abs_dx < 30 && abs_dy < 30 {
        SwipeDirection::Tap
    } else if abs_dx > abs_dy * 3 / 2 {
        if dx > 0 { SwipeDirection::Right } else { SwipeDirection::Left }
    } else if abs_dy > abs_dx * 3 / 2 {
        if dy > 0 { SwipeDirection::Down } else { SwipeDirection::Up }
    } else {
        SwipeDirection::Tap
    };

    let page = current_page();

    match direction {
        SwipeDirection::Tap => {
            if page == Page::Apps {
                // STORE AS PENDING INSTEAD OF EXECUTING INSTANTLY.
                *pending_tap = Some((start_x, start_y, embassy_time::Instant::now(), page));
                defmt::debug!("Tap pending…");
            } else {
                handle_page_tap(page, start_x, start_y).await;
            }
        }
        _ => {
            // ANY SWIPE CANCELS A PENDING TAP
            *pending_tap = None;
            defmt::debug!(
                "Swipe {:?} – Start: ({},{}) -> End: ({},{})",
                direction, start_x, start_y, last_x, last_y
            );
            handle_swipe(direction, page, start_x, start_y, last_x, last_y);
        }
    }
}

// ───────────────────────────────────────────────────────────────────────
// READ TOUCH
// RETURNS `Some(TouchPoint)` IF A FINGER IS ON THE DISPLAY OTHERWISE `None`
async fn read_touch() -> Option<TouchPoint> {
    critical_section::with(|cs| {
        let mut bus_ref = crate::I2C_BUS.borrow_ref_mut(cs);
        let i2c_bus = bus_ref.as_mut()?;
        let mut touch = crate::components::ft3168::Ft3168Touch::new(i2c_bus);
        touch.read().ok().flatten()
    })
}

// ───────────────────────────────────────────────────────────────────────
// HANDLE PAGE TAPS – USES THE MACRO-GENERATED DISPATCHER FOR SETTINGS PAGES
async fn handle_page_tap(page: Page, x: u16, y: u16) {
    // IF CONTROL CENTER IS VISIBLE - ALL TAPS GO THERE
    if crate::gui::control_center::is_visible() {
        if let Some(action) = crate::gui::control_center::handle_touch(x as i32, y as i32) {
            match action { // HIT AREAS
                // CC BOX 1
                crate::gui::TouchAction::ControlCenterBox1 => {
                    crate::base::wifi::toggle_wifi().await;
                    defmt::info!("CONTROL CENTER BOX1 PRESSED (WIFI)");
                } // CC BOX 2
                crate::gui::TouchAction::ControlCenterBox2 => {
                    crate::base::routes::api::settings::voice::state::toggle_voice().await;
                    defmt::info!("CONTROL CENTER BOX2 PRESSED (VOICE ASSISTANT TOGGLE)");
                } // CC BOX 3
                crate::gui::TouchAction::ControlCenterBox3 => {
                    crate::base::routes::api::settings::api::off::toggle_api().await;
                    defmt::info!("CONTROL CENTER BOX3 PRESSED");
                } // CC BOX 4
                crate::gui::TouchAction::ControlCenterBox4 => {                    
                    defmt::info!("CONTROL CENTER BOX4 PRESSED (SETTINGS)");
                    crate::store!(CURRENT_PAGE, 140);
                    crate::gui::control_center::close();
                }                 
                _ => {}
            }
        }
        return;
    }

    // TRY SETTINGS DISPATCH FIRST (HANDLES ALL PAGES WITH A `tap: module`)
    if let Some(action) = handle_settings_tap(page, x, y) {
        match action { // HIT AREAS
            crate::gui::TouchAction::SettingsToggle => {
                crate::base::wifi::toggle_wifi().await;
                defmt::info!("Wifi TOGGLED");
            }, // WIFI ON/OFF
            crate::gui::TouchAction::SettingsToggleWifi => {
                defmt::info!("WIFI TOGGLED");
                crate::swap!(crate::state::WIFI_STATE);
            }, // BLUETOOTH ON/OFF
            crate::gui::TouchAction::SettingsToggleBle => {
                defmt::info!("BLE TOGGLED");
                crate::swap!(crate::state::BLUETOOTH_STATE);
            }, // API ON/OFF
            crate::gui::TouchAction::SettingsToggleApi => {
                crate::base::routes::api::settings::api::off::toggle_api().await;
                defmt::info!("API TOGGLED");
            }, // MIC ON/OFF
            crate::gui::TouchAction::SettingsToggleMic => {
                if crate::load!(crate::state::MIC_VOLUME) == 0 {
                    crate::set_mic_gain(58);
                    crate::store!(crate::state::MIC_MUTED, false);
                } else {
                    crate::set_mic_gain(0);
                    crate::store!(crate::state::MIC_MUTED, true);
                }
                defmt::info!("MIC TOGGLED");
            }, // SPEAKER ON/OFF
            crate::gui::TouchAction::SettingsToggleSpeaker => {
                if crate::load!(crate::state::SPEAKER_VOLUME) == 0 {
                    crate::set_speaker_volume(58);
                    crate::store!(crate::state::SPEAKER_MUTED, false);
                } else {
                    crate::set_speaker_volume(0);
                    crate::store!(crate::state::SPEAKER_MUTED, true);
                }
                defmt::info!("SPEAKER TOGGLED");
            }, // WAKE WORD ON/OFF
            crate::gui::TouchAction::SettingsToggleWakeWord => {
                defmt::info!("WAKE WORD TOGGLED");
                crate::base::routes::api::settings::voice::wakeword::toggle_wake_word().await;
            }, // DISPLAY ON/OFF
            crate::gui::TouchAction::SettingsToggleDisplay => {
                defmt::info!("DISPLAY TOGGLED");
                crate::swap!(crate::state::DISPLAY_STATE);
            }, // AUDIO STREAMING ON/OFF
            crate::gui::TouchAction::SettingsToggleStreaming => {
                crate::base::routes::api::settings::speaker::stream::toggle_stream().await;
                defmt::info!("STREAMING TOGGLED");
            }, // AMPLIFIER ON/OFF
            crate::gui::TouchAction::SettingsToggleAmp => {
                crate::base::routes::api::settings::speaker::amp::toggle_amp();
                defmt::info!("AMP TOGGLED");
            }, // SSH SERVER ON/OFF         
            crate::gui::TouchAction::SettingsToggleSsh => {
                crate::base::ssh::toggle_ssh().await;
                defmt::info!("SSH TOGGLED");
            }, // VPN CLIENT ON/OFF
            crate::gui::TouchAction::SettingsToggleVpn => {
                crate::base::wireguard::toggle_vpn().await;
                defmt::info!("VPN TOGGLED");
            },            
            _ => {}
        }
        return;
    }

    // NON-SETTINGS PAGES (OR SETTINGS WITHOUT A TAP HANDLE)
    match page {
        Page::Weather => {
            crate::gui::weather::handle_touch(x as i32, y as i32);
        }
        Page::Settings => {
            let _ = crate::gui::settings::handle_touch(x as i32, y as i32);
        }
        Page::SettingsCpu   => { }
        Page::SettingsSleep => { }
        Page::SettingsInfo  => { }
        Page::SettingsSsh   => { }

        // MEDIA PLAYER PAGE
        Page::MediaPlayer => {
            // CHECK IF THE TAP IS A PLAYLIST TAP FIRST
            if crate::gui::media_player::is_split_open() {
                if let Some(index) = crate::gui::media_player::handle_playlist_tap(x as i32, y as i32) {
                    defmt::info!("PLAYLIST TAP ON INDEX {}", index);
                    let _ = crate::applications::media_player::PLAYBACK_CMD.send(crate::applications::media_player::PlaybackCommand::PlayTrack(index)).await;
                    // PLAYLIST DIRTY - REFRESH
                    crate::gui::media_player::invalidate_playlist();
                    // TAKE A BREATH & CLOSE THE SPLIT VIEW
                    //embassy_time::Timer::after(embassy_time::Duration::from_millis(150)).await;
                    crate::gui::media_player::close_split();
                    // SKIP NORMAL HIT-AREA HANDLE
                    return;
                }
            }
            
            // DEFINED HIT AREAS
            if let core::option::Option::Some(action) = crate::gui::media_player::handle_touch(
                x as i32, y as i32
            ) {
                match action { // HIT AREAS
                    // PREVIOUS TRACK
                    crate::gui::TouchAction::MediaPrev => {
                        crate::applications::media_player::prev().await;
                    } // PLAY / PAUSE
                    crate::gui::TouchAction::MediaPlayPause => {
                        crate::applications::media_player::play_pause().await;
                    } // NEXT TRACK
                    crate::gui::TouchAction::MediaNext => {
                        crate::applications::media_player::next().await;
                    } // HEART (ADD TO FAVOURITES)
                    crate::gui::TouchAction::MediaHeart => {
                        defmt::info!("MEDIA HEART TAPPED!");
                        crate::applications::media_player::heart().await;
                    } // CLEAR PLAYLIST
                    crate::gui::TouchAction::MediaClear => {
                        defmt::info!("MEDIA CLEAR TAPPED!");
                        crate::applications::media_player::clear().await;
                    } // SPLIT MEDIA PLAYER INTO PLAYLIST VIEW
                    crate::gui::TouchAction::MediaSplitView => {
                        if crate::gui::media_player::is_split_open() {
                            crate::gui::media_player::close_split();
                        } else { crate::gui::media_player::open_split(); }
                        defmt::debug!("SPLITTING MEDIA PLAYER VIEW!");
                    }
                    _ => {}
                }
            }
        }
        _ => {}
    }
}

// ───────────────────────────────────────────────────────────────────────
// TRY TO RETURN TO HOMESCREEN (CLOSE APP)
fn try_return_home(start_y: u16) -> bool {
    if start_y >= crate::state::LCD_HEIGHT - BOTTOM_SWIPE_THRESHOLD {
        defmt::info!("Closed app, back to clock page");
        let page = crate::gui::pages::current_page();
        if page == Page::MediaPlayer {
            crate::gui::media_player::release_playlist_cache();
        }
        set_page(Page::Clock);
        true
    } else { false }
}

// TRY TO CONTROL CENTER ON HOME
fn try_to_control_center_on_home(start_y: u16) -> bool {
    if start_y <= TOP_SWIPE_THRESHOLD {
        crate::gui::control_center::open();
        defmt::info!("Opening control center");
        true
    } else { false }
}

// ───────────────────────────────────────────────────────────────────────
// HANDLE SWIPE
fn handle_swipe(direction: SwipeDirection, page: Page, start_x: u16, start_y: u16, last_x: u16, last_y: u16) {
    // OPEN CONTROL CENTER FROM ANY PAGE
    if direction == SwipeDirection::Down
        && !crate::gui::control_center::is_visible()
        && start_y <= TOP_SWIPE_THRESHOLD
    {
        crate::gui::control_center::open();
        defmt::info!("Opening control center");
        return;
    }

    // LAUNCHER - FORWARD UP/DOWN/TAP TO ITS OWN HANDLER
    if page == Page::Apps {
        if direction != SwipeDirection::Left && direction != SwipeDirection::Right {
            crate::gui::apps::handle_swipe(direction);
            return;
        }
    }

    // IF CONTROL CENTER IS VISIBLE, SWIPE UP CLOSES IT
    if crate::gui::control_center::is_visible() && direction == SwipeDirection::Up {
        crate::gui::control_center::close();
        defmt::debug!("Closing control center");
        return;
    }

    // CLOSE MEDIA PLAYER SPLIT-VIEW FROM BOTTOM SWIPE
    if page == Page::MediaPlayer
        && direction == SwipeDirection::Up
        && crate::gui::media_player::is_split_open()
        && start_y >= crate::state::LCD_HEIGHT - BOTTOM_SWIPE_THRESHOLD
    {
        crate::gui::media_player::close_split();
        defmt::info!("Closed split view, staying on Media Player");
        return;
    }

    // IF MEDIA PLAYER IS SPLITTED INTO PLAYLIST VIEW
    // FORWARD UP/DOWN SWIPES TO ENABLE SCROLLING THE PLAYLIST
    if page == Page::MediaPlayer
        && crate::gui::media_player::is_split_open()
        && (direction == SwipeDirection::Up || direction == SwipeDirection::Down)
    {
        crate::gui::media_player::handle_swipe(direction);
        return;
    }

    // APP PAGES – SWIPE UP FROM BOTTOM CLOSE APP & GO HOME
    if page.is_app_page() && direction == SwipeDirection::Up {
        if try_return_home(start_y) {
            return;
        }
        if !page.is_settings_page() {
            return;
        }
    }

    // SETTINGS PAGES LEFT/RIGHT NAVIGATION + UP/DOWN DELEGATION
    if page.is_settings_page() {
        // INFO PAGE – ALL SWIPES GO THROUGH ITS OWN HANDLER FIRST
        if page == Page::SettingsInfo {
            let consumed = crate::gui::options::info::handle_swipe(direction, start_x, start_y, last_x, last_y);
            if consumed {
                return;
            }
        }

        match direction {
            SwipeDirection::Left => {
                let next = page.next_setting();
                set_page(next);
                defmt::debug!("Settings page changed to {:?}", next);
            }
            SwipeDirection::Right => {
                let prev = page.prev_setting();
                set_page(prev);
                defmt::debug!("Settings page changed to {:?}", prev);
            }
            SwipeDirection::Up | SwipeDirection::Down => {
                handle_settings_swipe(page, direction, start_x, start_y, last_x, last_y);
            }
            _ => {}
        }
        return;
    }

    // MAIN NAVIGATION
    match direction {
        SwipeDirection::Left => {
            let next = page.next_main();
            set_page(next);
            defmt::debug!("Page changed to {:?}", next);
        }
        SwipeDirection::Right => {
            let prev = page.prev_main();
            set_page(prev);
            defmt::debug!("Page changed to {:?}", prev);
        }
        _ => {}
    }
}

// ───────────────────────────────────────────────────────────────────────
// TOUCH TASK
// TASK SLEEPS UNTIL DISPLAY IS TURNED ON & FINGER IS ON SCREEN
#[embassy_executor::task]
pub async fn touch_task(mut touch_int: esp_hal::gpio::Input<'static>) {
    let mut tracking = false;
    let mut start_x = 0u16;
    let mut start_y = 0u16;
    let mut last_x = 0u16;
    let mut last_y = 0u16;

    let mut pending_tap: Option<(u16, u16, embassy_time::Instant, Page)> = None;

    loop {
        if !crate::load!(crate::state::DISPLAY_STATE) {
            touch_int.wait_for_low().await;
            crate::components::co5300::wake_up();
            crate::store!(crate::state::DISPLAY_STATE, true);
            crate::DISPLAY_CMD.send(crate::DisplayCommand::Start).await;
            crate::store!(crate::state::DISPLAY_TOUCH_ACTIVITY, true);
            crate::dirty!();
            embassy_time::Timer::after(embassy_time::Duration::from_millis(50)).await;
            continue;
        }

        if let Some((px, py, ptime, ppage)) = pending_tap {
            let elapsed = embassy_time::Instant::now().duration_since(ptime);
            let remaining = if elapsed < DOUBLE_TAP_TIMEOUT {
                DOUBLE_TAP_TIMEOUT - elapsed
            } else {
                embassy_time::Duration::from_millis(0)
            };

            match select(
                touch_int.wait_for_low(),
                embassy_time::Timer::after(remaining),
            ).await {
                Either::First(_) => {
                    tracking = true;
                    let fp = read_touch().await;
                    if let Some(tp) = fp {
                        start_x = tp.x;
                        start_y = tp.y;
                        last_x = tp.x;
                        last_y = tp.y;
                    }

                    loop {
                        if touch_int.is_low() {
                            if let Some(tp) = read_touch().await {
                                last_x = tp.x;
                                last_y = tp.y;
                            }
                            embassy_time::Timer::after(TRACKING_POLL_INTERVAL).await;
                            crate::dirty!();
                            continue;
                        }
                        if tracking {
                            let final_point = read_touch().await;
                            if final_point.is_none() {
                                tracking = false;
                                let dx = (start_x as i32 - px as i32).unsigned_abs();
                                let dy = (start_y as i32 - py as i32).unsigned_abs();
                                let time_ok = embassy_time::Instant::now().duration_since(ptime) <= DOUBLE_TAP_TIMEOUT;
                                let dist_ok = dx <= DOUBLE_TAP_MAX_DISTANCE as u32 && dy <= DOUBLE_TAP_MAX_DISTANCE as u32;
                                
                                if time_ok && dist_ok && ppage == Page::Apps && current_page() == Page::Apps {
                                    defmt::info!("👆👆");
                                    crate::store!(crate::state::DISPLAY_TOUCH_ACTIVITY, true);
                                    crate::gui::apps::handle_double_tap(start_x, start_y);
                                } else {
                                    if ppage == Page::Apps && current_page() == Page::Apps {
                                        defmt::debug!("👆");
                                        crate::store!(crate::state::DISPLAY_TOUCH_ACTIVITY, true);
                                        crate::gui::apps::handle_tap();
                                    }
                                    let now = embassy_time::Instant::now();
                                    let page = current_page();
                                    pending_tap = Some((start_x, start_y, now, page));
                                    continue;
                                }
                                pending_tap = None;
                            } else {
                                last_x = final_point.unwrap().x;
                                last_y = final_point.unwrap().y;
                                embassy_time::Timer::after(TRACKING_POLL_INTERVAL).await;
                                continue;
                            }
                        }
                        break;
                    }
                    continue;
                }
                Either::Second(_) => {
                    if ppage == Page::Apps && current_page() == Page::Apps {
                        defmt::info!("👆");
                        crate::store!(crate::state::DISPLAY_TOUCH_ACTIVITY, true);
                        crate::gui::apps::handle_tap();
                    }
                    pending_tap = None;
                    continue;
                }
            }
        }

        touch_int.wait_for_low().await;

        tracking = true;        
        let first_point = read_touch().await;
        crate::store!(crate::state::DISPLAY_TOUCH_ACTIVITY, true);
        if let Some(tp) = first_point {
            start_x = tp.x;
            start_y = tp.y;
            last_x = tp.x;
            last_y = tp.y;
            defmt::debug!("👆 START X={} Y={}", tp.x, tp.y);
        }

        loop {
            if touch_int.is_low() {
                crate::store!(crate::state::DISPLAY_TOUCH_ACTIVITY, true);
                if let Some(tp) = read_touch().await {
                    last_x = tp.x;
                    last_y = tp.y;
                    defmt::debug!("👆 MOVE X={} Y={}", tp.x, tp.y);
                }
                crate::store!(crate::state::DISPLAY_TOUCH_ACTIVITY, true);
                embassy_time::Timer::after(TRACKING_POLL_INTERVAL).await;
                continue;
            }
            if tracking {
                let final_point = read_touch().await;
                if final_point.is_none() {
                    tracking = false;
                    process_gesture(
                        start_x, start_y, last_x, last_y,
                        &mut pending_tap,
                    ).await;
                } else {
                    last_x = final_point.unwrap().x;
                    last_y = final_point.unwrap().y;
                    embassy_time::Timer::after(TRACKING_POLL_INTERVAL).await;
                    continue;
                }
            }
            break;
        }
    }
}
