# DOCKER IS USED TO PROVIDE EASY BUILD ENVIORMENT
# WHICH CAN BE HELL TO CONFIGURE FOR BEGINNERS/NIXOS USERS
services:
  watch:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    image: esp-dev:esp32s3box3
    # `docker exec -it esp32s3-watch /bin/bash`
    # TO EXEC INTO CONTAINER (for development)
    container_name: esp32s3-watch
    devices: # ENTER YOUR SERIAL PORT HERE
      - "/dev/ttyACM0:/dev/ttyACM0"
    environment:
      - CARGO_UNSTABLE_BUILD_STD=core
      # OPTIONAL ENV VARS CAN BE CONFIGURED HERE
    env_file:
      - ./.env # <- WRITE WiFi SSID/PASSWORD IN THIS FILE
      # USE THE `.env.example` FILE AS REFERENCE
    stdin_open: true
    tty: true
    # UNCOMMENT BELOW TO FLASH YOUR DEVICE AUTOMATICALLY AFTER THE DOCKER BUILD FINISHES
    # CONFIGURE SERIAL PORT AND `.env` BEFORE UNCOMMENTING
    #command: bash -c "source /root/export-esp.sh && cargo clean && cargo run --release"

