[target.xtensa-esp32s3-none-elf]
# COMMAND TO USE WHEN RUNNING `cargo run`
runner = "espflash flash --monitor --chip esp32s3 --log-format defmt"
# UNCOMMENT BELOW TO USE THE PARTITION TABLE DEFINED IN `partitions.csv`
#runner = "espflash flash --monitor --chip esp32s3 --partition-table=partitions.csv --log-format defmt"

# ───────────────────────────────────────────────────────────────────────
# FIRMWARE ENVIORMENT VARIABLES
# ALSO SET IN THE `docker-compose.yaml` FILE
[env]
DEFMT_LOG="info"

# ───────────────────────────────────────────────────────────────────────
# RUST BUILD FLAGS
[build]
rustflags = [
  "-C", "link-arg=-nostartfiles",
  "-Z", "stack-protector=all",
]
# `none` MEANS **NO** ESP-IDF 
target = "xtensa-esp32s3-none-elf"

# ───────────────────────────────────────────────────────────────────────
# NIGHTLY UNSTABLE
# BARE METAL: NO-STANDARD LIBRARIES
# BUT WE DO HOWEVER NEED `alloc` & `core`
[unstable]
build-std = ["alloc", "core"]

